version: '2'
services:
  site:
    #image: evns/grav
    build: .
    expose:
      - "80"
    environment:
      - DOMAIN=new.vivariumnovum.net    # set to your root/apex domain
      - GENERATE_CERTS=false  # set to true to automatically setup trusted ssl with let's encrypt
    env_file:
      - ./frontend.env
      - ./grav.env
    volumes:
      - ./backup:/var/www/grav-admin/backup
    networks:
      - frontend-web
networks:
  frontend-web:
    external: true
